"""update address table

Revision ID: 0408c06216f8
Revises: 3b35145ccee5
Create Date: 2026-08-02 16:50:32.674543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0408c06216f8'
down_revision: Union[str, Sequence[str], None] = '3b35145ccee5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('addresses_wilaya_id_fkey'), 'addresses', type_='foreignkey')
    op.drop_constraint(op.f('addresses_commune_id_fkey'), 'addresses', type_='foreignkey')
    op.create_foreign_key(None, 'addresses', 'communes', ['commune_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'addresses', 'wilayas', ['wilaya_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.create_foreign_key(op.f('addresses_commune_id_fkey'), 'addresses', 'communes', ['commune_id'], ['id'])
    op.create_foreign_key(op.f('addresses_wilaya_id_fkey'), 'addresses', 'wilayas', ['wilaya_id'], ['id'])
    # ### end Alembic commands ###
