"""add product image field

Revision ID: 09e578254312
Revises: d33099557501
Create Date: 2026-07-31 19:16:49.846308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09e578254312'
down_revision: Union[str, Sequence[str], None] = 'd33099557501'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_product_images_product_color_id'), 'product_images', ['product_color_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_images_product_color_id'), table_name='product_images')
    # ### end Alembic commands ###
