"""modif table wilaya , add table commune

Revision ID: 3b35145ccee5
Revises: eba4ea4d9021
Create Date: 2026-08-02 15:15:04.223367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b35145ccee5'
down_revision: Union[str, Sequence[str], None] = 'eba4ea4d9021'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communes', sa.Column('code', sa.Integer(), nullable=False))
    op.add_column('communes', sa.Column('name_ar', sa.String(length=100), nullable=False))
    op.add_column('communes', sa.Column('daira', sa.String(length=100), nullable=False))
    op.add_column('communes', sa.Column('daira_ar', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'communes', ['code'])
    op.add_column('wilayas', sa.Column('name_ar', sa.String(length=100), nullable=False))
    op.add_column('wilayas', sa.Column('home_shipping_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('wilayas', sa.Column('stopdesk_shipping_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.drop_column('wilayas', 'delivery_home')
    op.drop_column('wilayas', 'delivery_stopdesk')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wilayas', sa.Column('delivery_stopdesk', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('wilayas', sa.Column('delivery_home', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_column('wilayas', 'stopdesk_shipping_price')
    op.drop_column('wilayas', 'home_shipping_price')
    op.drop_column('wilayas', 'name_ar')
    op.drop_constraint(None, 'communes', type_='unique')
    op.drop_column('communes', 'daira_ar')
    op.drop_column('communes', 'daira')
    op.drop_column('communes', 'name_ar')
    op.drop_column('communes', 'code')
    # ### end Alembic commands ###
