"""change wishlist table

Revision ID: 4300b340677d
Revises: cf797b8afa72
Create Date: 2026-08-04 00:20:53.585599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4300b340677d'
down_revision: Union[str, Sequence[str], None] = 'cf797b8afa72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_product_wishlist', 'wishlists', ['user_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_product_wishlist', 'wishlists', type_='unique')
    # ### end Alembic commands ###
