"""wilaya name_ar nullable

Revision ID: 590f8c037ffe
Revises: 0323d86b2d47
Create Date: 2026-09-24 13:26:26.308749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '590f8c037ffe'
down_revision: Union[str, Sequence[str], None] = '0323d86b2d47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_variants', 'sku',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_unique_constraint('uq_product_variant_color_size', 'product_variants', ['product_color_id', 'size_id'])
    op.alter_column('wilayas', 'name_ar',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wilayas', 'name_ar',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint('uq_product_variant_color_size', 'product_variants', type_='unique')
    op.alter_column('product_variants', 'sku',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
