"""change review  table

Revision ID: 5a1cab795af3
Revises: 4300b340677d
Create Date: 2026-08-05 22:28:31.915764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a1cab795af3'
down_revision: Union[str, Sequence[str], None] = '4300b340677d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_unique_constraint('uq_user_product_review', 'reviews', ['user_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_product_review', 'reviews', type_='unique')
    op.drop_column('reviews', 'updated_at')
    # ### end Alembic commands ###
