"""shipping rate add

Revision ID: 5c19879fb223
Revises: e679117427f7
Create Date: 2026-08-24 11:31:50.840086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c19879fb223'
down_revision: Union[str, Sequence[str], None] = 'e679117427f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipping_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wilaya_id', sa.Integer(), nullable=False),
    sa.Column('shipping_method_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['shipping_method_id'], ['shipping_methods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wilaya_id'], ['wilayas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wilaya_id', 'shipping_method_id', name='uq_shipping_rate_wilaya_method')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipping_rates')
    # ### end Alembic commands ###
