"""add product image field

Revision ID: 70f4bcb17753
Revises: 09e578254312
Create Date: 2026-08-01 11:21:00.724536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70f4bcb17753'
down_revision: Union[str, Sequence[str], None] = '09e578254312'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_product_color', 'product_colors', ['product_id', 'color_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_product_color', 'product_colors', type_='unique')
    # ### end Alembic commands ###
