"""commune optional fields

Revision ID: 8e76e3655599
Revises: 590f8c037ffe
Create Date: 2026-09-24 13:36:32.433608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e76e3655599'
down_revision: Union[str, Sequence[str], None] = '590f8c037ffe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('communes', 'code',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('communes', 'name_ar',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('communes', 'daira',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('communes', 'daira_ar',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('communes', 'daira_ar',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('communes', 'daira',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('communes', 'name_ar',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('communes', 'code',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
