"""add product fields

Revision ID: acf1ff8ebb47
Revises: ac5632e015be
Create Date: 2026-07-30 19:20:38.607537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acf1ff8ebb47'
down_revision: Union[str, Sequence[str], None] = 'ac5632e015be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sku', sa.String(length=50), nullable=False))
    op.add_column('products', sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('products', sa.Column('compare_at_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('stock', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('weight', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('is_new', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_column('products', 'is_new')
    op.drop_column('products', 'weight')
    op.drop_column('products', 'stock')
    op.drop_column('products', 'compare_at_price')
    op.drop_column('products', 'base_price')
    op.drop_column('products', 'sku')
    # ### end Alembic commands ###
