"""modif table product variant

Revision ID: ba23652662b3
Revises: 733b13d9c505
Create Date: 2026-08-01 12:18:15.449831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba23652662b3'
down_revision: Union[str, Sequence[str], None] = '733b13d9c505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('product_variants_sku_key'), 'product_variants', type_='unique')
    op.create_index(op.f('ix_product_variants_id'), 'product_variants', ['id'], unique=False)
    op.create_index(op.f('ix_product_variants_sku'), 'product_variants', ['sku'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_variants_sku'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_id'), table_name='product_variants')
    op.create_unique_constraint(op.f('product_variants_sku_key'), 'product_variants', ['sku'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
