"""update shipping method table

Revision ID: bb4b9838366d
Revises: 0408c06216f8
Create Date: 2026-08-02 17:02:27.178964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb4b9838366d'
down_revision: Union[str, Sequence[str], None] = '0408c06216f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipping_methods', sa.Column('estimated_days', sa.Integer(), nullable=False))
    op.add_column('shipping_methods', sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('shipping_methods', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipping_methods', 'is_active')
    op.drop_column('shipping_methods', 'base_price')
    op.drop_column('shipping_methods', 'estimated_days')
    # ### end Alembic commands ###
