"""change coupon table

Revision ID: cf797b8afa72
Revises: 9021219065c4
Create Date: 2026-08-04 00:17:43.590974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf797b8afa72'
down_revision: Union[str, Sequence[str], None] = '9021219065c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupons', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('coupons', sa.Column('maximum_discount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('coupons', sa.Column('usage_per_user', sa.Integer(), nullable=False))
    op.add_column('coupons', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('coupons', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('coupons_code_key'), 'coupons', type_='unique')
    op.create_index(op.f('ix_coupons_code'), 'coupons', ['code'], unique=True)
    op.create_index(op.f('ix_coupons_id'), 'coupons', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coupons_id'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_code'), table_name='coupons')
    op.create_unique_constraint(op.f('coupons_code_key'), 'coupons', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_column('coupons', 'updated_at')
    op.drop_column('coupons', 'created_at')
    op.drop_column('coupons', 'usage_per_user')
    op.drop_column('coupons', 'maximum_discount')
    op.drop_column('coupons', 'name')
    # ### end Alembic commands ###
