"""update order table

Revision ID: ea612567f66a
Revises: bb4b9838366d
Create Date: 2026-08-02 17:26:10.507450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea612567f66a'
down_revision: Union[str, Sequence[str], None] = 'bb4b9838366d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('product_image', sa.String(length=500), nullable=True))
    op.alter_column('order_items', 'product_variant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('order_items_product_variant_id_fkey'), 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'product_variants', ['product_variant_id'], ['id'], ondelete='SET NULL')
    op.add_column('orders', sa.Column('wilaya', sa.String(length=100), nullable=False))
    op.add_column('orders', sa.Column('commune', sa.String(length=100), nullable=False))
    op.add_column('orders', sa.Column('shipping_method', sa.String(length=100), nullable=False))
    op.add_column('orders', sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('orders', sa.Column('payment_method', sa.String(length=50), nullable=False))
    op.add_column('orders', sa.Column('payment_status', sa.String(length=50), nullable=False))
    op.add_column('orders', sa.Column('coupon_code', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('orders', 'city')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('orders', 'updated_at')
    op.drop_column('orders', 'coupon_code')
    op.drop_column('orders', 'payment_status')
    op.drop_column('orders', 'payment_method')
    op.drop_column('orders', 'discount')
    op.drop_column('orders', 'shipping_method')
    op.drop_column('orders', 'commune')
    op.drop_column('orders', 'wilaya')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key(op.f('order_items_product_variant_id_fkey'), 'order_items', 'product_variants', ['product_variant_id'], ['id'])
    op.alter_column('order_items', 'product_variant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('order_items', 'product_image')
    # ### end Alembic commands ###
