"""modif table wilaya , add table commune

Revision ID: eba4ea4d9021
Revises: ba23652662b3
Create Date: 2026-08-01 12:54:07.366865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eba4ea4d9021'
down_revision: Union[str, Sequence[str], None] = 'ba23652662b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wilaya_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['wilaya_id'], ['wilayas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communes_id'), 'communes', ['id'], unique=False)
    op.add_column('addresses', sa.Column('wilaya_id', sa.Integer(), nullable=False))
    op.add_column('addresses', sa.Column('commune_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'addresses', 'communes', ['commune_id'], ['id'])
    op.create_foreign_key(None, 'addresses', 'wilayas', ['wilaya_id'], ['id'])
    op.drop_column('addresses', 'city')
    op.add_column('wilayas', sa.Column('delivery_home', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('wilayas', sa.Column('delivery_stopdesk', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('wilayas', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_wilayas_id'), 'wilayas', ['id'], unique=False)
    op.drop_column('wilayas', 'home_delivery_price')
    op.drop_column('wilayas', 'office_delivery_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wilayas', sa.Column('office_delivery_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('wilayas', sa.Column('home_delivery_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_wilayas_id'), table_name='wilayas')
    op.drop_column('wilayas', 'is_active')
    op.drop_column('wilayas', 'delivery_stopdesk')
    op.drop_column('wilayas', 'delivery_home')
    op.add_column('addresses', sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.drop_column('addresses', 'commune_id')
    op.drop_column('addresses', 'wilaya_id')
    op.drop_index(op.f('ix_communes_id'), table_name='communes')
    op.drop_table('communes')
    # ### end Alembic commands ###
